export const blogData = [
  {
    id: 1,
    title: "HTML",
    body: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero amet maxime debitis earum neque, odio quidem, dolorum odit sequi ab nam accusamus doloremque quod eum quaerat recusandae mollitia. Error necessitatibus dolores molestiae aliquid corrupti, id quas aspernatur tenetur blanditiis ducimus alias at voluptatem sequi quis tempore facere rerum quia. Quibusdam, distinctio! Id voluptas praesentium voluptates, amet, optio provident modi esse ad facilis ab sed necessitatibus, dolores aperiam voluptatem recusandae. Necessitatibus illo, velit a ab id quisquam dicta dolor unde ad laudantium eveniet commodi earum dolore debitis voluptate similique quia harum corrupti laborum consectetur esse. Eum aperiam veniam molestias placeat officiis praesentium. Magni quae corporis architecto rem suscipit enim totam, voluptates impedit aspernatur, optio veniam, sequi numquam veritatis accusamus esse doloribus dolore ab quia quaerat sit ad facere blanditiis illo dolorem? A laudantium natus repellendus, esse voluptatem corrupti unde nesciunt ut! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero amet maxime debitis earum neque, odio quidem, dolorum odit sequi ab nam accusamus doloremque quod eum quaerat recusandae mollitia. Error necessitatibus dolores molestiae aliquid corrupti, id quas aspernatur tenetur blanditiis ducimus alias at voluptatem sequi quis tempore facere rerum quia. Quibusdam, distinctio! Id voluptas praesentium voluptates, amet, optio provident modi esse ad facilis ab sed necessitatibus, dolores aperiam voluptatem recusandae. Necessitatibus illo, velit a ab id quisquam dicta dolor unde ad laudantium eveniet commodi earum dolore debitis voluptate similique quia harum corrupti laborum consectetur esse. Eum aperiam veniam molestias placeat officiis praesentium. Magni quae corporis architecto rem suscipit enim totam, voluptates impedit aspernatur, optio veniam, sequi numquam veritatis accusamus esse doloribus dolore ab quia quaerat sit ad facere blanditiis illo dolorem? A laudantium natus repellendus, esse voluptatem corrupti unde nesciunt ut!",
  },
  {
    id: 2,
    title: "CSS",
    body: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero amet maxime debitis earum neque, odio quidem, dolorum odit sequi ab nam accusamus doloremque quod eum quaerat recusandae mollitia. Error necessitatibus dolores molestiae aliquid corrupti, id quas aspernatur tenetur blanditiis ducimus alias at voluptatem sequi quis tempore facere rerum quia. Quibusdam, distinctio! Id voluptas praesentium voluptates, amet, optio provident modi esse ad facilis ab sed necessitatibus, dolores aperiam voluptatem recusandae. Necessitatibus illo, velit a ab id quisquam dicta dolor unde ad laudantium eveniet commodi earum dolore debitis voluptate similique quia harum corrupti laborum consectetur esse. Eum aperiam veniam molestias placeat officiis praesentium. Magni quae corporis architecto rem suscipit enim totam, voluptates impedit aspernatur, optio veniam, sequi numquam veritatis accusamus esse doloribus dolore ab quia quaerat sit ad facere blanditiis illo dolorem? A laudantium natus repellendus, esse voluptatem corrupti unde nesciunt ut!",
  },
  {
    id: 3,
    title: "JavaScript",
    body: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero amet maxime debitis earum neque, odio quidem, dolorum odit sequi ab nam accusamus doloremque quod eum quaerat recusandae mollitia. Error necessitatibus dolores molestiae aliquid corrupti, id quas aspernatur tenetur blanditiis ducimus alias at voluptatem sequi quis tempore facere rerum quia. Quibusdam, distinctio! Id voluptas praesentium voluptates, amet, optio provident modi esse ad facilis ab sed necessitatibus, dolores aperiam voluptatem recusandae. Necessitatibus illo, velit a ab id quisquam dicta dolor unde ad laudantium eveniet commodi earum dolore debitis voluptate similique quia harum corrupti laborum consectetur esse. Eum aperiam veniam molestias placeat officiis praesentium. Magni quae corporis architecto rem suscipit enim totam, voluptates impedit aspernatur, optio veniam, sequi numquam veritatis accusamus esse doloribus dolore ab quia quaerat sit ad facere blanditiis illo dolorem? A laudantium natus repellendus, esse voluptatem corrupti unde nesciunt ut!",
  },
  {
    id: 4,
    title: "Bootstrap",
    body: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero amet maxime debitis earum neque, odio quidem, dolorum odit sequi ab nam accusamus doloremque quod eum quaerat recusandae mollitia. Error necessitatibus dolores molestiae aliquid corrupti, id quas aspernatur tenetur blanditiis ducimus alias at voluptatem sequi quis tempore facere rerum quia. Quibusdam, distinctio! Id voluptas praesentium voluptates, amet, optio provident modi esse ad facilis ab sed necessitatibus, dolores aperiam voluptatem recusandae. Necessitatibus illo, velit a ab id quisquam dicta dolor unde ad laudantium eveniet commodi earum dolore debitis voluptate similique quia harum corrupti laborum consectetur esse. Eum aperiam veniam molestias placeat officiis praesentium. Magni quae corporis architecto rem suscipit enim totam, voluptates impedit aspernatur, optio veniam, sequi numquam veritatis accusamus esse doloribus dolore ab quia quaerat sit ad facere blanditiis illo dolorem? A laudantium natus repellendus, esse voluptatem corrupti unde nesciunt ut!",
  },
  {
    id: 5,
    title: "React",
    body: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero amet maxime debitis earum neque, odio quidem, dolorum odit sequi ab nam accusamus doloremque quod eum quaerat recusandae mollitia. Error necessitatibus dolores molestiae aliquid corrupti, id quas aspernatur tenetur blanditiis ducimus alias at voluptatem sequi quis tempore facere rerum quia. Quibusdam, distinctio! Id voluptas praesentium voluptates, amet, optio provident modi esse ad facilis ab sed necessitatibus, dolores aperiam voluptatem recusandae. Necessitatibus illo, velit a ab id quisquam dicta dolor unde ad laudantium eveniet commodi earum dolore debitis voluptate similique quia harum corrupti laborum consectetur esse. Eum aperiam veniam molestias placeat officiis praesentium. Magni quae corporis architecto rem suscipit enim totam, voluptates impedit aspernatur, optio veniam, sequi numquam veritatis accusamus esse doloribus dolore ab quia quaerat sit ad facere blanditiis illo dolorem? A laudantium natus repellendus, esse voluptatem corrupti unde nesciunt ut!",
  },
];
